service: my-express-application

provider:
  name: aws
  runtime: node.js20.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SESSION_SECRET: ${env:SESSION_SECRET}

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
